binop_separator = "Front"
blank_lines_upper_bound = 2
combine_control_expr = false
comment_width = 80
empty_item_single_line = false
error_on_line_overflow = false
force_multiline_blocks = true
imports_indent = "Block"
imports_layout = "HorizontalVertical"
indent_style = "Block"
match_block_trailing_comma = true
max_width = 120
normalize_comments = true
reorder_impl_items = true
report_fixme = "Always"
report_todo = "Unnumbered"
use_field_init_shorthand = true
use_small_heuristics = true
use_try_shorthand = true
where_single_line = true
wrap_comments = true
