language: minimal

os:
  - linux

services:
  - docker

env:
  - DOCKER_IMAGE=howtocards/backend

before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

jobs:
  include:
    - stage: build
      script:
        - docker build -t $DOCKER_IMAGE:$TRAVIS_COMMIT .
        - docker images
        - docker push $DOCKER_IMAGE:$TRAVIS_COMMIT
    - stage: push latest
      if: branch = master AND type != pull_request
      script:
        - docker pull $DOCKER_IMAGE:$TRAVIS_COMMIT
        - docker tag $DOCKER_IMAGE:$TRAVIS_COMMIT $DOCKER_IMAGE:latest
        - docker push $DOCKER_IMAGE:latest
    - stage: push nightly
      if: branch = dev AND type != pull_request
      script:
        - docker pull $DOCKER_IMAGE:$TRAVIS_COMMIT
        - docker tag $DOCKER_IMAGE:$TRAVIS_COMMIT $DOCKER_IMAGE:nightly
        - docker push $DOCKER_IMAGE:nightly
    - stage: push tag
      if: tag =~ /^v\d+\.\d+\.\d+/
      script:
        - docker pull $DOCKER_IMAGE:$TRAVIS_COMMIT
        - docker tag $DOCKER_IMAGE:$TRAVIS_COMMIT $DOCKER_IMAGE:$TRAVIS_TAG
        - docker push $DOCKER_IMAGE:$TRAVIS_TAG
