language: minimal

os:
  - linux

env:
  - CRATE_NAME=public-api
  - CRATE_NAME=internal-api

services:
  - docker

before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

jobs:
  include:
    - stage: build
      script:
        - ./build-image.sh $CRATE_NAME

        - docker images

    - stage: push latest
      if: branch = master AND type != pull_request
      script:
        - ./build-tag.sh $CRATE_NAME latest

    - stage: push nightly
      if: branch = dev AND type != pull_request
      script:
        - ./build-tag.sh $CRATE_NAME nightly

    - stage: push tag
      if: tag =~ /^howtocards-public-api\/\d+\.\d+\.\d+/
      script:
        - ./build-tag.sh public-api $TRAVIS_TAG

    - stage: push tag
      if: tag =~ /^howtocards-internal-api\/\d+\.\d+\.\d+/
      script:
        - ./build-tag.sh internal-api $TRAVIS_TAG
