language: minimal

os:
  - linux

services:
  - docker

env:
  - DOCKER_IMAGE=howtocards/backend

jobs:
  include:
    - stage: build
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t $DOCKER_IMAGE:$TRAVIS_COMMIT .
        - docker images
        - docker push $DOCKER_IMAGE:$TRAVIS_COMMIT:$TRAVIS_COMMIT
    - stage: push latest
      if:
        - branch = master
      script:
        - docker pull $DOCKER_IMAGE:$TRAVIS_COMMIT
        - docker tag $DOCKER_IMAGE:$TRAVIS_COMMIT $DOCKER_IMAGE:latest
        - docker push $DOCKER_IMAGE:latest
    - stage: push nightly
      if:
        - branch = dev
      script:
        - docker pull $DOCKER_IMAGE:$TRAVIS_COMMIT
        - docker tag $DOCKER_IMAGE:$TRAVIS_COMMIT $DOCKER_IMAGE:nightly
        - docker push $DOCKER_IMAGE:nightly
    - stage: push tag
      if:
        - tag =~ /^v\d+\.\d+\.\d+/
      script:
        - docker pull $DOCKER_IMAGE:$TRAVIS_COMMIT
        - docker tag $DOCKER_IMAGE:$TRAVIS_COMMIT $DOCKER_IMAGE:$TRAVIS_TAG
        - docker push $DOCKER_IMAGE:$TRAVIS_TAG
