[package]
name = "howtocards_backend"
version = "0.1.1"
authors = ["Sergey Sova <mail@sergeysova.com>"]

[[bin]]
name = "howtocards_server"
path = "./src/main.rs"

[lib]
name = "howtocards"
crate-type = ["dylib", "rlib", "staticlib"]

[dependencies]
actix-web = "0.6"
serde = "1.0.66"
serde_derive = "1.0.66"
serde_json = "1.0.20"
env_logger = "0.5.10"
uuid = "0.6.5"
r2d2 = "0.8.2"
dotenv = "0.13.0"
diesel = { version = "1.1.0", features = ["sqlite", "r2d2"] }
failure = "0.1.1"
ron = "0.2.2"
sha2 = "0.7.1"
notify-rust = "3.4.2"

[dependencies.rustbreak]
version = "2.0.0-rc2"
features = ["ron_enc"]
