[package]
name = "howtocards_backend"
version = "0.1.2"
authors = ["Sergey Sova <mail@sergeysova.com>"]
license = "MIT"
description = "Application library for howtocards service"

[[bin]]
name = "howtocards_server"
path = "./src/main.rs"

[lib]
name = "howtocards"
crate-type = ["dylib", "rlib", "staticlib"]

[dependencies]
actix = "0.7.4"
actix-web = "0.7.*"
diesel = { version = "1.3.3", features = ["postgres", "r2d2"] }
dotenv = "0.13.0"
env_logger = "0.5.10"
failure = "0.1.1"
futures = "0.1.23"
notify-rust = "3.4.2"
r2d2 = "0.8.2"
ron = "0.2.2"
rustbreak = { version = "2.0.0-rc2", features = ["ron_enc"] }
serde = "1.0.66"
serde_derive = "1.0.66"
serde_json = "1.0.20"
sha2 = "0.7.1"
uuid = { version = "0.7.1", features = ["serde", "v4"]  }
