[package]
name = "howtocards_backend"
version = "0.1.0"
authors = ["Sergey Sova <mail@sergeysova.com>"]

[dependencies]
actix-web = "0.6"
serde = "1.0.66"
serde_derive = "1.0.66"
serde_json = "1.0.20"
